INSERT INTO APP_USER (ID, FIRST_NAME, LAST_NAME, BIRTH_DATE, SHOE_SIZE) VALUES (1, 'Sam', 'Berg', '1990-03-13', 12);
INSERT INTO APP_USER (ID, FIRST_NAME, LAST_NAME, BIRTH_DATE, SHOE_SIZE) VALUES (2, 'Shaquille', 'O''Neal', '1972-03-06', 23);
INSERT INTO APP_USER (ID, FIRST_NAME, LAST_NAME, BIRTH_DATE, SHOE_SIZE) VALUES (3, 'Tinker', 'Bell', '1904-12-27', 0.1);
